### ISSUE TITLE
`CalculateWrappedString` race condition

### ISSUE THREAD

**Issue by lumpn** [sinbad/SUDSExample#1]
### Problem
There is a problem with `CalculateWrappedString` if called too early. `LineText->GetCachedGeometry().GetLocalSize()` will be zero, resulting in no text wrapping.

### How to reproduce
Edit `Dlg_FAQExample.sud` and make the _first_ speaker line really long. At least 500 letters. Play in editor.

### Result
The typewriter text will not wrap.

### How to fix
In `BP_PlayerController`, delay calling `Start Dialogue` by two(!) ticks. That way the UI has enough time to get laid out properly so that `GetCachedGeometry()` will work.

Another workaround is when the _first_ speaker line fits well within one line without wrapping. In that case `CalculatedWrappedString` will still be wrong but the result is just the same. Any subsequent speaker lines will wrap properly because the UI had enough time to get laid out.

Obviously delaying by two ticks is not a great fix. I'm not sure if there's any better option though.

**Comment by sinbad** [comment]
Thanks for reporting, I fixed this internally in the typewriter text widget here: https://github.com/sinbad/StevesUEHelpers/commit/0c92bcbaa81f143925aa2a796167e8b1cae63e41
